### ISSUE TITLE
Old sample sheets can't be parsed

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#174]
While retrying a lot of failed runs for issue #113, I saw several runs where the sample sheet could not be parsed: 09 Jul 2013, 05 Jul 2013, 28 Jun 2013, 21 Jun 2013, 11 Jun 2013, 26 Apr 2013, 25 Apr 2013, and 9 Apr 2013.

Most runs, including 9 Jul 2013 had this error in the MISEQ_MONITOR_OUTPUT.log:

```
2015-02-20 22:07:19.462304 - [ERROR] Parsing sample sheet failed - skipping run /media/RAW_DATA/MiSeq/runs/130709_M01841_0009_000000000-A3RV9/
Traceback (most recent call last):
  File "MISEQ_MONITOR.py", line 159, in <module>
    run_info = sample_sheet_parser(sample_sheet)
  File "/usr/local/share/miseq/production/sample_sheet_parser.py", line 118, in sample_sheet_parser
    is_research = (desc_subfield_tokens[1] == 'TRUE')
IndexError: list index out of range
```

26 and 25 Apr 2013 had this error:

```
2015-02-20 22:08:22.442119 - [ERROR] Parsing sample sheet failed - skipping run /media/RAW_DATA/MiSeq/runs/130426_M01841_0003_000000000-A3FGN/
Traceback (most recent call last):
  File "MISEQ_MONITOR.py", line 159, in <module>
    run_info = sample_sheet_parser(sample_sheet)
  File "/usr/local/share/miseq/production/sample_sheet_parser.py", line 103, in sample_sheet_parser
    desc = tokens[header.index('Description')]
IndexError: list index out of range
```

09 Apr 2013 had this error:

```
2015-02-20 22:08:22.704956 - [ERROR] Parsing sample sheet failed - skipping run /media/RAW_DATA/MiSeq/runs/130409_M01841_0001_000000000-A40KG/
Traceback (most recent call last):
  File "MISEQ_MONITOR.py", line 159, in <module>
    run_info = sample_sheet_parser(sample_sheet)
  File "/usr/local/share/miseq/production/sample_sheet_parser.py", line 41, in sample_sheet_parser
    key, value = tokens[:2]
ValueError: need more than 1 value to unpack
```

**Comment by donkirkby** [comment]
We haven't had any requests to process those old runs in the last three years, so I'm going to close this issue again.
