### ISSUE TITLE
badCigar field in coord_ins.csv file throws TypeError

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/MiCall#401]
We've been running the current pipeline (commit e6eafca6aff2479ae0d8f64e9e6c0b49f2c55b07) on some data and ran into this problem when calling `aln2counts.py`:
```
Traceback (most recent call last):
  File "micall/core/aln2counts.py", line 1120, in <module>
    main()
  File "micall/core/aln2counts.py", line 1117, in main
    remap_conseq_csv=args.remap_conseq_csv)
  File "micall/core/aln2counts.py", line 1094, in aln2counts
    report.read_insertions(conseq_ins_csv)
  File "micall/core/aln2counts.py", line 423, in read_insertions
    pos = int(row['pos'])
TypeError: int() argument must be a string or a number, not 'NoneType'
```
which appears to be caused by the following lines in the our `*.conseq_ins.csv` file:
```
M00388:345:000000000-B395M:1:2119:21464:11075,R,HIV1B-pol-seed,2632,A,6
00388:345:000000000-B395M:1:1101:5219:4261,badCigar
M00388:345:000000000-B395M:1:1101:12165:5614,badCigar
```
No idea why one of the `M`s was dropped from the `qname` on the second line.  Anyhow, lines with `badCigar` obviously have the wrong number of items.  I'll look into how these entries are getting generated in `sam2aln.py`.

**Comment by ArtPoon** [comment]
I think the user on our side somehow got `sam2aln` to write `failed_list` into the `insert_writer` output.  Confirming before closing.

**Comment by ArtPoon** [comment]
PEBKAC.  Closing  :-)
