### ISSUE TITLE
Too many open files in sam2aln

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#437]
While processing a pair of 1.5GB FASTQ files for E99725-PR-RT_S44 in the 9 Jul 2014 run, the sam2aln step opened too many temporary files. I guess we'll have to close the temporary files, and then clean them up at the end. Alternatively, could we record where each cache section starts, and then open the file several times for reading?

    Traceback (most recent call last):
      File "/path/to/Sandboxes/userXXX_run1234_LLadke/step6/sam2aln.py", line 500, in <module>
      File "/path/to/Sandboxes/userXXX_run1234_LLadke/step6/sam2aln.py", line 496, in main
      File "/path/to/Sandboxes/userXXX_run1234_LLadke/step6/sam2aln.py", line 461, in sam2aln
      File "/path/to/Sandboxes/userXXX_run1234_LLadke/step6/micall/utils/big_counter.py", line 29, in __setitem__
      File "/path/to/Sandboxes/userXXX_run1234_LLadke/step6/micall/utils/big_counter.py", line 32, in _write_cache
      File "/usr/lib64/python3.4/tempfile.py", line 521, in TemporaryFile
      File "/usr/lib64/python3.4/tempfile.py", line 207, in _mkstemp_inner
    OSError: [Errno 24] Too many open files: '/path/to/Sandboxes/userXXX_run1234_LLadke/step6/output_data/merged_seq_countsv81dy4v8.csv'

**Comment by donkirkby** [comment]
Interestingly, PyCharm seems to raise the soft limit on open files up to the hard limit. I ran this script in PyCharm, and it successfully opened many thousands of files:

    from tempfile import TemporaryFile
    from time import sleep
    
    open_files = []
    while True:
        file_count = len(open_files)
        if file_count % 100 == 0:
            print('Opened {} files.'.format(file_count), flush=True)
            sleep(1)
        f = TemporaryFile(mode='w+', prefix='file_test', suffix='.csv')
        f.write('This is file number {}.'.format(file_count))
        open_files.append(f)

Running in the Ubuntu terminal, it died after 1000 open files.

To check the operating system limits for number of open files (soft limit and hard limit):

```
$ ulimit -n && ulimit -Hn
1024
1048576
```

To check the limit in Python:
    import resource
    
    print(resource.getrlimit(resource.RLIMIT_NOFILE))

In PyCharm, the output is:

    (1048576, 1048576)

In the terminal:

    (1024, 1048576)

I guess PyCharm raises the limit so it can index source files more efficiently, but that setting gets passed on to the Python processes.
