### ISSUE TITLE
Too many open files when counting

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#457]
Sample E99725 from the 09-Jul-2014.M01841 run is very large (3.1GB of compressed FASTQ files). It raises this error:

```
Traceback (most recent call last):
  File "/opt/micall/micall_kive.py", line 114, in <module>
    main()
  File "/opt/micall/micall_kive.py", line 105, in main
    sample.process(pssm, force_gzip=True)  # dataset files change .gz to .raw
  File "/opt/micall/micall/drivers/sample.py", line 205, in process
    conseq_region_csv=conseq_region_csv)
  File "/opt/micall/micall/core/aln2counts.py", line 1128, in aln2counts
    report.process_reads(g2p_aligned_csv, aligned_csv, coverage_summary)
  File "/opt/micall/micall/core/aln2counts.py", line 328, in process_reads
    self.read(aligned_reads, v3_overlap_region_name)
  File "/opt/micall/micall/core/aln2counts.py", line 364, in read
    self._count_reads(aligned_reads)
  File "/opt/micall/micall/core/aln2counts.py", line 165, in _count_reads
    self.insert_writer.add_nuc_read('-'*offset + nuc_seq, count)
  File "/opt/micall/micall/core/aln2counts.py", line 976, in add_nuc_read
    self.nuc_seqs[offset_sequence] += count
  File "/opt/micall/micall/utils/big_counter.py", line 29, in __setitem__
    self._write_cache()
  File "/opt/micall/micall/utils/big_counter.py", line 32, in _write_cache
    cache = TemporaryFile(mode='w+', prefix=self.file_prefix, suffix='.csv')
  File "/usr/lib64/python3.4/tempfile.py", line 521, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib64/python3.4/tempfile.py", line 207, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 24] Too many open files: '/mnt/output/nuc_read_countstxr2hk9c.csv'
```

We should probably close the temporary files used by `BigCounter`. The run used 1.1GB of memory, so we probably don't want to increase the size of the temporary files.

**Comment by donkirkby** [comment]
There are some relevant notes in issue #437 where we found the same problem. We solved that one by not counting identical sequences anymore. The most important point is that you can't reproduce this problem when running in PyCharm.

**Comment by donkirkby** [comment]
I reproduced the problem by running `micall_basespace.py` on the 09-Jul-2014.M01841 run with only sample E99725 in place. It ran for 14 hours with a maximum resident memory of 200MB.
