### ISSUE TITLE
BaseSpace API endpoint stopped working

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#476]
We currently fetch the list of samples in a BaseSpace run to check that all the samples came from that run before we use the phiX error rate to censor the sample files. Unfortunately, it looks like we used an [undocumented endpoint], and it has stopped working.

Steps to reproduce:

1. Choose the MiCall app on BaseSpace, and click the Launch Application button.
2. Choose a run, choose a biosample, and choose a project to save the results in.
3. Click the Launch Application button.

Expected results: run the analysis, including censoring the reads based on the phiX error rate data from the run.

Actual results: an error in the output log like this:

```
2019-07-16 18:40:13.214515 - [DEBUG](urllib3.connectionpool) https://api.basespace.illumina.com:443 "GET /v1pre3/runs/*******/samples?Offset=0&access_token=*******&Limit=1000 HTTP/1.1" 500 312
Traceback (most recent call last):
  File "/opt/micall/micall_basespace.py", line 761, in <module>
    main()
  File "/opt/micall/micall_basespace.py", line 725, in main
    [s["Id"] for s in run_json.samples])
  File "/opt/micall/micall_basespace.py", line 161, in check_run_sample_ids
    sample_set = set().union(*[self._get_all_sample_ids_from_run_id(runid) for runid in run_id_lst])
  File "/opt/micall/micall_basespace.py", line 161, in <listcomp>
    sample_set = set().union(*[self._get_all_sample_ids_from_run_id(runid) for runid in run_id_lst])
  File "/opt/micall/micall_basespace.py", line 145, in _get_all_sample_ids_from_run_id
    jobj = self._runssamples(runid, DOWNLOAD_BATCH_SIZE, numgot)
  File "/opt/micall/micall_basespace.py", line 132, in _runssamples
    raise RuntimeError("runsamples API error")
RuntimeError: runsamples API error
```

This code was originally added for #358 to find samples within a run.

The short term workaround is to not select a run. This won't let users censor reads based on the phiX error rate, but everything else should work.

Long term, it looks like we can use the [run properties] to get the list of samples in a run. We might need to get a list of biosamples instead of samples.

Even longer term, MiCall might be a lot easier to use if we work on #389 to get phiX error rates from undetermined FASTQ files.

[run properties]: https://developer.basespace.illumina.com/community/discussion?place=msg%2Fbasespace-developers%2FlqnLfaO8l0g%2Fr4Kuoh43vGQJ
[undocumented endpoint]: https://developer.basespace.illumina.com/community/discussion?place=msg%2Fbasespace-developers%2FSetw4dS7c2w%2FuZjKceJfCAAJ

**Comment by donkirkby** [comment]
I removed the run chooser from the BaseSpace form until this is fixed. Here's the removed field definition:

```
        {
            "$type": "RunChooser",
            "size": 250,
            "label": "Run",
            "required": false,
            "id": "run-id",
            "helpText": "A run does not have to be provided, however run quality information can only be produced if the selected samples were from the provided run"
        },
```
