### ISSUE TITLE
Accept unknown project codes

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#498]
Users occasionally ask to set up a new project code, because they want to change some of the settings in QAI. Right now, MiCall just crashes during the upload to QAI if it doesn't recognize a project code.

```
2019-12-13 14:08:58[INFO]micall.monitor.kive_watcher.collate_folder(): Collating results in /mnt/data/don/data/RAW_DATA/MiSeq/runs/191213_M01841/Results/version_7.12
2019-12-13 14:08:58[INFO]update_qai.process_folder(): Uploading data to Oracle from /mnt/data/don/data/RAW_DATA/MiSeq/runs/191213_M01841/Results/version_7.12
2019-12-13 14:08:58[WARNING]update_qai.build_conseqs(): Failed to load project seeds.
Traceback (most recent call last):
  File "/mnt/data/don/git/MiCall/micall/monitor/update_qai.py", line 90, in build_conseqs
    seeds = projects.getProjectSeeds(entry['target_project'])
  File "/mnt/data/don/git/MiCall/micall/core/project_config.py", line 115, in getProjectSeeds
    for region in self.config['projects'][project_name]['regions']:
KeyError: 'TCR'
2019-12-13 14:08:58[WARNING]update_qai.build_conseqs(): Failed to load project seeds.
Traceback (most recent call last):
  File "/mnt/data/don/git/MiCall/micall/monitor/update_qai.py", line 90, in build_conseqs
    seeds = projects.getProjectSeeds(entry['target_project'])
  File "/mnt/data/don/git/MiCall/micall/core/project_config.py", line 115, in getProjectSeeds
    for region in self.config['projects'][project_name]['regions']:
KeyError: 'TCR'
2019-12-13 14:08:58[WARNING]update_qai.build_conseqs(): Failed to load project seeds.
Traceback (most recent call last):
  File "/mnt/data/don/git/MiCall/micall/monitor/update_qai.py", line 90, in build_conseqs
    seeds = projects.getProjectSeeds(entry['target_project'])
  File "/mnt/data/don/git/MiCall/micall/core/project_config.py", line 115, in getProjectSeeds
    for region in self.config['projects'][project_name]['regions']:
KeyError: 'TCR'
2019-12-13 14:08:58[WARNING]update_qai.build_conseqs(): Failed to load project seeds.
Traceback (most recent call last):
  File "/mnt/data/don/git/MiCall/micall/monitor/update_qai.py", line 90, in build_conseqs
    seeds = projects.getProjectSeeds(entry['target_project'])
  File "/mnt/data/don/git/MiCall/micall/core/project_config.py", line 115, in getProjectSeeds
    for region in self.config['projects'][project_name]['regions']:
KeyError: 'TCR'
```

It looks like we had this problem before, and we fixed it in #385. This must be a regression.

* [ ] Stop warning about "Unknown" project code.
* [ ] Add run folder and sample name to warning message.

**Comment by donkirkby** [comment]
If we decide that a warning is useful, it should include information about which run and sample had the problem.

Workaround: look at the time stamp on the error e-mail, and find the run name in `micall.log`.

**Comment by donkirkby** [comment]
This isn't actually a regression, because the results do get uploaded to QAI. The only problem is that it's sending e-mails that aren't helpful. Stop warning about the project code "Unknown", and include information about run folder and sample name when we warn about any other unknown project codes.
