### ISSUE TITLE
Batch collated only one sample

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiCall#534]
A user had locked one of the CSV files in the scratch folder while a batch was being processed, and that caused an error when the batch finished and tried to clean up. It looks like it might be a problem coordinating between the threads in the MiCall watcher.

When the last sample finished processing, the MiCall watcher tried to collate all the result files and remove the scratch folder, but it reported this error:

```
2020-02-28 13:40:07[INFO]micall.monitor.kive_watcher.collate_folder(): Collating results in /media/RAW_DATA/MiSeq/runs/200214_M01841_0404_000000000-CLJ9D/Results/version_7.1
2
2020-02-28 13:42:26[ERROR]micall.monitor.kive_watcher.wait_for_retry(): Waiting 0:00:05 before retrying.
Traceback (most recent call last):
  File "/usr/local/share/MiCall/micall/monitor/kive_watcher.py", line 495, in poll_runs
    results_path = self.collate_folder(folder_watcher)
  File "/usr/local/share/MiCall/micall/monitor/kive_watcher.py", line 537, in collate_folder
    shutil.rmtree(scratch_path)
  File "/usr/lib64/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'conseq.csv'
```

About 30 seconds later, it starts processing the first sample of that run again, when it should just be retrying the collation.

### Workaround
Stop the MiCall watcher service, delete the `doneprocessing` file, and start it up again. It should download all the results and collate again.

**Comment by donkirkby** [comment]
Fixed in c33d3425ec5eb20ec36d74b40d675542ed5f8688.
