### ISSUE TITLE
Resistance runs failing for Covid

### ISSUE THREAD

**Issue by CBeelen** [cfe-lab/MiCall#793]
The resistance runs are failing for the Covid test samples with the following traceback:
```
Traceback (most recent call last):
  File "/opt/micall/micall_kive_resistance.py", line 68, in <module>
    main()
  File "/opt/micall/micall_kive_resistance.py", line 65, in main
    sample_group.process_resistance(RunInfo([sample_group]))
  File "/opt/micall/micall/drivers/sample_group.py", line 57, in process_resistance
    report_resistance(amino_csv,
  File "/opt/micall/micall/resistance/resistance.py", line 647, in report_resistance
    write_nuc_mutations(nuc_csv, nuc_mutations_csv)
  File "/opt/micall/micall/resistance/resistance.py", line 488, in write_nuc_mutations
    wild_type = ref_seq[nuc_pos-1]
IndexError: string index out of range
```
Looks like there is a refseq position in `nuc.csv` that is out of bounds - I'm looking through it to find out what happened and why.

**Comment by CBeelen** [comment]
Solved by 3ceb954 - the regions were getting cut short by a call to `landmark_reader.get_gene` with the default of `drop_stop_codon=True`. Setting it to False solved this issue, and the refs positions are not out of bounds anymore.
